### ISSUE TITLE
Will not work on windows

### ISSUE THREAD

**Issue by phoenixperry** [b-g/processing-sublime#17]
I get this error on Build. 

[Error 2] The system cannot find the file specified
[cmd:  [u'processing-java', u'--sketch=C:\Users\phoenix\Documents\Processing\basic.pde', u'--output=C:\Users\phoenix\Documents\Processing\basic\build-tmp', u'--run', u'--force']]
[dir:  C:\Users\phoenix\Documents\Processing\basic]
[path: C:\Users\phoenix\Documents\processingTwo]
[Finished]

In sysdm.cpl I added the following to the environmental variables > User variables for phoenix  
path = C:\Users\phoenix\Documents\processingTwo 

Thoughts? I even tried spelling processing differently to make sure it wasn't some character issue.

**Comment by dvekedy** [comment]
Dear gentelmen,

I have carefully read your posts, but unfortunately did not understand how to solve the sama problem.

I have the following message in Sublime Text 2:

"[Error 2] 
[cmd:  [u'processing-java', u'--sketch=', u'--output=/build-tmp', u'--run', u'--force']]
[dir:  C:\Windows\System32]
[path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\]
[Finished]"

What does it mean?

Please, could you explain to me, as a child, :)  what step by step I need to take to solve the problem with preocessing-java.

I have:
Windows 8.1 x64
The latest version Processing x 32 and Sublime Text 2 x64

I would be very grateful for any help and tips!

**Comment by b-g** [comment]
Hi @dvekedy!

You have to install the processing command line tool (processing-java) to your windows. The error message basically says "sublime text can't run processing-java in the command line". Please carefully check and read: https://github.com/b-g/processing-sublime#windows

Hope that helps!
B

**Comment by foong** [comment]
hi guys, i have tried all the steps from the read me, it works fine for my windows 8 but it doesnt seem to work on my laptop with windows 7, without "Processing (Windows).sublime-build" but adding environmental variables it gives me this error.

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\FOONG\AppData\Local\Temp\jna-FOONG\jna9100761614979794647.dll: Access is denied
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(Unknown Source)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:752)
	at com.sun.jna.Native.loadNativeLibrary(Native.java:737)
	at com.sun.jna.Native.<clinit>(Native.java:129)
	at processing.app.platform.WindowsPlatform.<clinit>(WindowsPlatform.java:503)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at processing.app.Base.initPlatform(Base.java:239)
	at processing.mode.java.Commander.main(Commander.java:74)
[Finished in 0.9s with exit code 1]

I've tired adding in the "Processing (Windows).sublime-build"
and it says, error trying to parse built system, invalid escape.....
and i have tried both of the built above.

i also tried directing it to processing-java.exe instead of just processing-2.2.1
in the environmental variables. any help and tips?

**Comment by b-g** [comment]
Hi @foong! Sorry to hear that this is such an hustle for you ... but could you please confirm whether you can run 'processing-java' on the windows command line without problems? Basically the Processing Bundle for Sublime Text just calls this command every time you press 'build'.

**Comment by foong** [comment]
i tried in command prompt and this erro came out.
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\FOONG\AppData\Local\Temp\jna-FOONG\jna9100761614979794647.dll: Access is denied
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary1(Unknown Source)
at java.lang.ClassLoader.loadLibrary0(Unknown Source)
at java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.lang.Runtime.load0(Unknown Source)
at java.lang.System.load(Unknown Source)
at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:752)
at com.sun.jna.Native.loadNativeLibrary(Native.java:737)
at com.sun.jna.Native.(Native.java:129)
at processing.app.platform.WindowsPlatform.(WindowsPlatform.java:503)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at processing.app.Base.initPlatform(Base.java:239)
at processing.mode.java.Commander.main(Commander.java:74)
what does it mean?

**Comment by b-g** [comment]
@foong Then I'm afraid it is a processing-java command line tool error ... which has nothing to do with the processing bundel for sublime text. I furthermore have no idea what this means. Sorry! Maybe ask in the processing forum?

**Comment by foong** [comment]
@b-g Oh, alright then, i will. Really appreciate the help. Thanks again!

**Comment by jripp122** [comment]
am using the build system from @MAKIO135, when I ctrl+b it outputs 

> Finished.
> [Finished in 1.5s]

but does not run the sketch. What am I doing wrong here?

**Comment by ybakos** [comment]
@jripp122 Please specify the version of Processing you're using, and your OS. Also, try running _processing-java_ manually to see if it works. Lastly, ask @MAKIO135 .

**Comment by ganiodayo** [comment]
@jripp122 When it says "Finished" without actually building anything it is usually because you have white space in your file/folder names or you began the name with a number.

**Comment by KnowledgeableKangaroo** [comment]
Hello, bg. I know I can just open it through processing, but I like the sublime text editor better. The output of a pde file outputs, when I use the processing package that I installed from the readme, this:
[WinError 2] The system cannot find the file specified
[cmd: ['processing-java', '--force', '--sketch=C:\\Users\\nsmvsingh\\Documents\\Sublime Text\\GitHub\\supreme-guacamole\\calculator', '--run']]
[dir: C:\Users\nsmvsingh\Documents\Sublime Text\GitHub\supreme-guacamole\calculator]
[path: C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Users\nsmvsingh\AppData\Local\Microsoft\WindowsApps;C:\Users\nsmvsingh\AppData\Roaming\npm;C:\Users\nsmvsingh\AppData\Local\GitHubDesktop\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;]

i am using this code and made it .pde
How do I fix this?
Thanks,
Varun

**Comment by KnowledgeableKangaroo** [comment]
Hi again, bg. I figured out that it was because my sublime text folder had spaces. I fixed that and now it just says
Finished
[Finished in 1.2s]

**Comment by Quillbert** [comment]
I used makio135's build system, but when I tried to build, nothing happened, and it said no build system next to the line and column numbers. I know I had the build system selected. Does anybody know what could be wrong?

**Comment by KnowledgeableKangaroo** [comment]
@Quillbert one mistake I had made was making the path to processing and not processing-java.

**Comment by Quillbert** [comment]
I checked the path, but it still says no build system.

**Comment by KnowledgeableKangaroo** [comment]
Can you send me the code for the sublime-build you used

**Comment by Quillbert** [comment]
I used this code:

`{
"path": "$file_path\temp",
"cmd": [
"C:\Users\andrewhamby22\Desktop\processing-3.4\processing-java.exe",
"--sketch=$file_path",
"--output=$file_path/build",
"--force",
"--build",
"--run"]
}`

**Comment by KnowledgeableKangaroo** [comment]
I:

1. Put the path to processing in the environmental variable
2. Downloaded the zip of the processing (which I don't think helped)
3. CTRL - P and installed the processing package. 
4. Ran it with this processing package anddeleted processing (widnows)

**Comment by Quillbert** [comment]
I tried using this package with the path, but it just got me an error. Command Prompt is disabled on my computer, and I was wondering if that could be the problem.

**Comment by shreym03** [comment]
> @jripp122 When it says "Finished" without actually building anything it is usually because you have white space in your file/folder names or you began the name with a number.

Is there a way I can work around this error. My username for the file path ( _C:\Users\Shrey Mathur\Documents\Processing_ ) has the whitespace in it and I feel like it's better for the build to work at any location rather than a specific one

**Comment by amytraylor** [comment]
I meant specifically the file and folder with your Processing sketch in it.

Also be careful not to name projects the same name as a class used inside.

And check to make sure all your assets are actually in the data folder and they are spelled exactly the same as you have written them in the code. You might want to check the properties of each asset because sometimes a jpeg extension will actually be JPEG in the properties. Processing should tell you when you are missing assets but sometimes it missed.

On Apr 11, 2019 7:17 AM, shreym03 <notifications@github.com> wrote:

@jripp122 When it says "Finished" without actually building anything it is usually because you have white space in your file/folder names or you began the name with a number.

Is there a way I can work around this error. My username for the file path ( C:\Users\Shrey Mathur\Documents\Processing ) has the whitespace in it and I feel like it's better for the build to work at any location rather than a specific one

**Comment by shreym03** [comment]
@amytraylor No, the problem is with is because of the file path. I think I should clarify why I came to the conclusion.
So I tried the build and got the same issue as @AOEU1234. So I went to the command prompt, went to the file where path where processing-java was ( which is in a public folder **_C:\Program Files\processing-3.5.3_**). And  I typed the code 
`C:\Program Files\processing-3.5.3>processing-java.exe --sketch=C:\Users\Shrey Mathur\Documents\Processing\sketch_190411a --output=C:\Users\Shrey Mathur\Documents\Processing\sketch_190411a/build --force  --run`
I got the error
**_C:\Users\Shrey does not exist_**

I then tried the same thing with quotes around the white space (`...\" Shrey Mathur"\...`) and then it seemed to work. But I don't know how to translate that to the file path in the sublime build. Any suggestions as to what to try?

P. S. I tried putting quotes around the file path variable (`..."--sketch=\"$file_path\"",...`) and that didn't seem to work.

**Comment by hijomojo** [comment]
> I then tried the same thing with quotes around the white space (`...\" Shrey Mathur"\...`) and then it seemed to work. But I don't know how to translate that to the file path in the sublime build. Any suggestions as to what to try?
> 
> P. S. I tried putting quotes around the file path variable (`..."--sketch=\"$file_path\"",...`) and that didn't seem to work.

I've had this same issue as you and @AOEU1234 (just in case ... sorry for the necropost)

What I've just found is that sublime's $file_path handles spaces in paths just fine, so you don't need to try to add more "" into the path (unless you're personally running it in CMD, as you found). 

What I had to do was remove "--build" from the command for it to actually run. the --run option includes everything --build does, but it appears that having --build in there seems to cancel --run. I've just tested this in both cmd and sublime and it works in both.

I also had to change all the '\' for '/' in the path to processing-java.exe

**Comment by hijomojo** [comment]
For anyone interested in the future, here is another sublime-build which will kill the previously built running window of your sketch (if you didn't manually close it), then build and run a new one. This makes 'Build' much more like using 'Run' in the Processing IDE.

You'll need to use `\\` for `\` and `\"` for `"` in your paths as `shell_cmd` requires special characters like those to be escaped.

Obviously, also swap this bit: `DRIVE:\\YOUR\\PATH\\TO\\processing-x.x.x\\processing-java.exe` with the correct path to processing-java.exe for your computer.

    {
    	"path": "$file_path\temp",
    	"shell_cmd": "C:\\Windows\\System32\\Taskkill.exe /FI \"WINDOWTITLE eq $file_base_name\" /F && DRIVE:\\YOUR\\PATH\\TO\\processing-x.x.x\\processing-java.exe --sketch=\"$file_path\" --output=\"$file_path\\build\" --force --run"
    }

**Comment by designcode360** [comment]
Darn spaces! 

I'm on a PC running Windows 10. Pulling my hair out trying to get Processing to build from Sublime text 3. The "problem" was a SPACE in my folder name. My error is I followed a tutorial in which the instructor was using a MAC. Mental note!! NEVER use Spaces on a PC.
