### ISSUE TITLE
Color/syntax problem with classes? I could be wrong.

### ISSUE THREAD

**Issue by shmup** [b-g/processing-sublime#20]
Not even sure how to word this, heh. You'll see from the attached screenshot that the closing curly brace on any class has a .. color that extends the width. It's the same color I get for trailing whitespace, but there aren't actually any spaces there.

The fix I'm doing at the moment, just to spare my eyes, is throwing a semicolon at the end. 

Curious if you had any thoughts. I've tried with a few themes, and it happens with any of them. It's what made me think it was related to ```Processing.tmLanguage``` but I have no idea.

![image](https://f.cloud.github.com/assets/118710/375372/f6ee98e4-a3ba-11e2-97ea-4c8daec4b412.png)
![image](https://f.cloud.github.com/assets/118710/375378/162b31f4-a3bb-11e2-8cc8-9128598fd879.png)

**Comment by Frozenfire92** [comment]
+1 this irked me as well, if I get a chance I will have a look further

**Comment by kylefleming** [comment]
@ybakos is spot on with the C++ directive.

The short answer of why this is happening is that the whole processing file is being parsed as if it was a c++ file, so it highlights keywords, but it also gives an error if, for example, you don't have a semicolon at the end of your class definition. In essence anything inside of a function or a class is being styled as C++ and nothing in the tmLanguage file after the C++ directive makes a difference to the parsing of the file, except for things outside of a set of { } brackets, for example import lines.

Taking out the C++ directive broke other parts of the styling because now it was being styled as a Java file, and the styling for java doesn't do nearly as much styling around function calls (which is the reason why all the function calls turned white in your screen shot in #68 )

The problem there is that you can't inherit styling from another lexer (i.e. java) and extend it to add new embedded functionality (like adding processing keywords that get styled inside of a java class). You can only take the other language's style exactly as is, and anything you add will only affect root stuff. For example, if you use a processing keyword like background() for example, it will style as a processing keyword if it's outside of a function, and style as a C++ keyword if it's inside of a function. This is a pretty big problem in my opinion, because it means most of what's inside the tmLanguage file is actually doing nothing, and the only 2 things that do anything are the C++ and java lines, where it styles it like a mix of c++ and java, not as an extended java syntax, which is what processing really is.

One simple bandaid solution would be to change the line from including C++ to including C instead. That would preserve a lot of the things you said got broken, since any top level functions would still be styled like a C function and any classes would change from styling like C++ to styling like Java. It would preserve things like the function keywords (only in top level functions like setup()), but would stop it from requiring a semicolon at the end of a class. Unfortunately though anything inside of a class definition would now be styled as a pure java class and the styling would change (since java's styling is very lacking in my opinion). It's certainly not ideal, because you would still have inconsistent styling throughout.

The only real solution to all of this is to copy the java tmLanguage rules, and to readapt them for the processing community, adding function call styling, like C++/C has. Until that happens, there will continue to be weird styling errors since processing is not based on C++.

As an alternative, someone could submit a pull request to the built-in java language lexer to add better styling, which would in turn help the processing lexer, allowing us to remove the dependency on C++ styling without feeling like we've lost color.

**Comment by kylefleming** [comment]
Here's an example if C++ is changed to C.

C++ version:
![screen shot 2015-06-16 at 4 42 01 pm](https://cloud.githubusercontent.com/assets/192120/8196952/a998acac-1446-11e5-8b0d-5dda1576dbc6.png)

C version:
![screen shot 2015-06-16 at 4 42 07 pm](https://cloud.githubusercontent.com/assets/192120/8196953/adb352e2-1446-11e5-9b93-7eb3059a2e3e.png)

Notice `configureUI()` stops being styled because it's inside of a class, so it changes to being styled as java, but `background()` continues to be styled, because it's in a top level function (`setup()`) and so is styled as C.

For reference, this is the version without C++, so it's pure java:
![screen shot 2015-06-16 at 4 42 12 pm](https://cloud.githubusercontent.com/assets/192120/8196954/b1111226-1446-11e5-8931-182aa0d75fa4.png)

Notice here, that neither `configureUI()` nor `background()` are styled, because they're both being recognized as pure java, which again doesn't style function calls.

The main thing I want to illustrate is that the reason the styling gets worse if you remove C++, is that java's lexer just doesn't style as many things as the C/C++ ones do. Also that changing it to C makes parts of it better but it still has problems, just different kinds.

**Comment by b-g** [comment]
Hi @kylefleming,

Many thanks for the investigation! Finally I get a grasp of what is going on. Do you think you can fix it completely?

If not ... and as the whole thing seems to be endless and nobody is keen to maintain it (including myself) ... I would vote to remove the processing vocabulary highlighting completely from the bundle and just go with the standard java highlighting style.

Opinions?
@ybakos
@shmup 
@Frozenfire92 
@bertbalcaen

**Comment by kylefleming** [comment]
I'll gladly try. My plan is to rewrite it as I described above to be based on Java with some added stylings to be more like what we have now. I'll let you know when I have something that works the way we want it, possibly the next few weeks.

**Comment by b-g** [comment]
@kylefleming 👍 That would be mega! Looking forward!

**Comment by ybakos** [comment]
@kylefleming I am so glad that this has irked someone else besides me.

I agree that a pure syntax definition for highlighting without the C/C++ dependency would be ideal. However, if this proves to be not worth the effort, then I recommend replacing C++ with C.

**Comment by ybakos** [comment]
I naively think the path of least resistance here is to:

1. Remove the source.c++ include.
2. Add what we need from source.c++ to get syntax within class & method definitions correct.

**Comment by kylefleming** [comment]
Just for reference, the problem is that you can't actually "extend" another included source. You can import it wholesale, but you can't add to the inner layers of it, so the only way to add to it in the way we want is to copy everything over from java (hence #77).

**Comment by b-g** [comment]
Solved https://github.com/b-g/processing-sublime/commit/589fb572402862bd97b376ec9eaaf4e8e53d67e2
