### ISSUE TITLE
Proposal for new build system

### ISSUE THREAD

**Issue by b-g** [b-g/processing-sublime#73]
Hi @akaleeroy, @Sparragus, @ybakos,

Started this issue as a new thread to join the build system discussion which we had all over the place.

Based on your feedback I tweaked yesterdays proposal once more. I also changed my mind and kicked out all the legacy stuff. The goal would be to have just a simply single build system which works for p2 and p3. With the benefits of less confusion and a working 'automatic' build system. I also very much like the Re-run feature of @akaleeroy which should be included in any case IMO.

Please check once more everything for p2 and p3 https://github.com/b-g/processing-sublime/commit/6d08ebbab28e7561836115ec2413f590a56c1d12 (bg-dev branch)

Feedback and ideas are very welcome ...

@ybakos should we also add a dedicated build system for the sake of consistency in Processing.sublime-build for the upcoming Java Ant Project feature?

Many thanks!
B

**Comment by ybakos** [comment]
@b-g Adding a build command for the Ant-style project isn't necessary, since folks will use the Ant build system. But I will checkout the bg-dev branch and see if it makes sense.

**Comment by ybakos** [comment]
I am a fan of having only one build system plus variants, but this doesn't seem to include @mckennapsean 's build system for [P3 here](https://github.com/b-g/processing-sublime/pull/51) which omits the need for the `build-tmp` output configuration.

Personally, I don't care since I don't use it. And maybe it should wait until Processing 3 is production-ready.

**Comment by Sparragus** [comment]
@b-g 
It isn't working for me on:
  - Processing 3.0a10 (processing-java build 0237)
  - Processing 3.0a9 (processing-java build 0236)

It does work well on:
  - Processing 2.2.1 (processing-java build 0227)
  - Processing 3.0a5 (processing-java build 0232)

It was all tested on OS X. As another note, Processing 3.0a9 is the earliest version on the download page with the updated IDE. I also was not able to build it from the command line, so the bug is on their side. Perhaps we should file a bug report.

I agree with @ybakos that we shouldn't mind too much with Processing 3, at least not yet.

**Comment by mckennapsean** [comment]
I can confirm that processing-java is not working in Processing 3's latest alphas for Mac OS X (Yosemite here). I will double-check on Windows later... they have made a lot of major changes to their codebase since last fall. It could also be related to the debug mode. Anyways, this is likely a bug to report to their team.

As for the build system I proposed, I support this new simpler solution of a single build system for P2 & P3. However, I would also recommend having a new variant be written for Processing 3 only, for just running the sketch (no temp folder). It could be named "Run sketch (Processing 3 only)", and the only difference from the default option is that it would not have an output specified instead going straight to the system's temp folder. Personally, the other variants I would use less often and having access to the build output can be useful at times (like in the case of exporting to an application for debugging). This additional variant could be used by those who have newer versions of Processing and wish to opt out of having a build folder.

My motivation behind having an option which leaves no build folder is when using a version control system with developing a Processing project. I considered adding this *build-tmp* folder to a popular [gitignore repository](https://github.com/github/gitignore), but anyone can name the *build-tmp* folder whatever they wish so that seemed less than optimal. I also felt that adding a .gitignore statement for this folder for every Processing project or even in a global gitignore was less than optimal. So I submitted a pull request to make the output folder be optional to the Processing team, which was adopted into the Processing 3 codebase. The way they work is to mainly push forward new releases... not propagate features into older versions. So while the change could have been used for Processing 2, they are not releasing any new "features" to that version as far as I know. Lately, I have been using Processing less & less, but I just wanted to explain my initial motivation behind all of this.

**Comment by ybakos** [comment]
Great. @b-g let's relegate the Processing 3 build command as a variant for now as @mckennapsean suggests. Later, once Processing 3 is the production release, we can relegate the Processing 2 scheme as a variant, and promote the Processing 3 build command as the primary one.

**Comment by akaleeroy** [comment]
Works for me on:
- Processing 2.2.1 (processing-java build 0227) on Windows x64
- Processing 3.0a9 (processing-java build 0236) on Windows x64
- Processing 3.0a10 (processing-java build 0237) on Windows x64 (but that doesn't matter because their `size()` fix doesn't work, making all sketches take up the entire screen and therefore rendering Processing from Sublime Text unusable)

@mckennapsean I'm a little confused about the output folder debate here. If system temp folder output is desired, like Processing 3 offers, there is one way to give this option for all versions: specify `--output=/tmp/p5-build-tmp` for OS X and Linux and `--output=%TEMP%\\p5-build-tmp` for Windows. 
I wasn't backing this up because I was under the impression that some people use the .java and .class files from the build-tmp folder, but it seems they're more of a problem (Dropbox, git). And come to think of it, there's `--export` if you want those!

So I say away with the temp files, to the system temp folder.

**Comment by mckennapsean** [comment]
True! I was really hoping Processing would just automatically fill in the system temp folder for you... but apparently they won't support this in P2 :frowning: so we gotta hack this functionality into our tools.

If the *build-tmp* output folder is still desired, you could add a variant: "Build & run sketch".

**Comment by b-g** [comment]
Hi all!

:+1: 

Many thanks for feedback, thoughts and testing!!

I just added as discussed the "Run sketch (Processing 3 only)" variant. 

Once P3 is then in production we get rid of `--output` in all variants and just add a single "Build & run sketch (use always for old P2 sketches)" variant with the `--output` parameter ... better wording is welcome :)

All good? If yes ... I will merge the bg-dev branch after the weekend.

Cheers!

**Comment by Sparragus** [comment]
All good! 👌🏽

On Friday, June 19, 2015, Benedikt Groß <notifications@github.com> wrote:

> Hi all!
>
> [image: :+1:]
>
> Many thanks for feedback, thoughts and testing!!
>
> I just added as discussed the "Run sketch (Processing 3 only)" variant.
>
> Once P3 is then in production we get rid of --output in all variants and
> just add a single "Build & run sketch (use always for old P2 sketches)"
> variant with the --output parameter ... better wording is welcome :)
>
> All good? If yes ... I will merge the bg-dev branch after the weekend.
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/b-g/processing-sublime/issues/73#issuecomment-113540527>
> .
>


-- 
Richard Kaufman

**Comment by ybakos** [comment]
Works fine for me.

**Comment by akaleeroy** [comment]
Watch out, `Run sketch (Processing 3 only)` does `--present` instead of `--run`. 
We've been mulling this over entirely too long. :smile:

**Comment by b-g** [comment]
@akaleeroy Damn! Will fix it! 😀 Thanks for spotting!

**Comment by b-g** [comment]
Done. Merged dev branch with the master:
https://github.com/b-g/processing-sublime/commit/27cf937d179c2687403ec983efa0ae215b562a47
