### ISSUE TITLE
Can't find processing-java

### ISSUE THREAD

**Issue by fredguth** [b-g/processing-sublime#81]
I followed instructions, tried Tools>Build, but ST2 console says it can't find file or directory.
See the error here: https://www.evernote.com/l/AZQ1T9k27VhAu4wpjSai6YzxJu_Dx8h53Iw

Notice that I do have processing-java installed as requested.

I am just alerting, because other users might find the same error. But I solved my problem.

Solved by going to ~Library/Application Support/Sublime Text 2/Packages/Processing/Build Systems and altering the builder with the complete path of my processing-java install.

**Comment by b-g** [comment]
:) Thanks for the hints!

**Comment by fredguth** [comment]
welcome!

Em qui, 3 de set de 2015 às 03:16, Benedikt Groß <notifications@github.com>
escreveu:

> :) Thanks for the hints!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/b-g/processing-sublime/issues/81#issuecomment-137346750>
> .
>
-- 
Fred Guth

**Comment by ybakos** [comment]
@dvschultz @levitabris I have looked into this more and am now able to replicate the issue. The problem is how Sublime does not use your user shell's `PATH` configuration on OSX. To fix this, use Package Manager to install the "Fix Mac Path" package.

This occurs with Processing 3 and not Processing 2, because Processing 3 installs `processing-java` in _/usr/local/bin_ whereas Processing 2 installed it in _usr/bin_.

**Comment by fredguth** [comment]
Thanks!
