### ISSUE TITLE
No such file or directory: 'processing-java'

### ISSUE THREAD

**Issue by dvschultz** [b-g/processing-sublime#86]
Working in Sublime Text 3 (3083) and processing-java (Processing 0244) on a Mac I’m seeing this error when building (all four build options)

```
[Errno 2] No such file or directory: 'processing-java'
[cmd: ['processing-java', '--force', '--sketch=/Users/derrick/Desktop/hype_basics/step1/build', '--output=/Users/derrick/Desktop/hype_basics/step1/build/build-tmp', '--present']]
[dir: /Users/derrick/Desktop/hype_basics/step1/build]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
```

however when I run that command directly from Terminal (`processing-java --force --sketch=/Users/derrick/Desktop/hype_basics/step1/build --run`) it works as expected. 

Have tried restarting ST3 and my machine.

Something I’m doing wrong here?

**Comment by dvschultz** [comment]
update: looks like it works if I use `Build With...` > `Re-run sketch` but not with the other build with options

**Comment by levitabris** [comment]
I guess it's because the ST failed to find *processing-java* in the paths *[path: /usr/bin:/bin:/usr/sbin:/sbin]*, which is located in *usr/local/bin* on Mac. I tried with moving the file to one of the listed paths but it seems to be conflicted with osx's security policy. 

Supposedly, we can either 1) create a alias in the folder like *usr/bin* or 2) edit the path of ST to access the right file location.

Somebody have a better solution?

**Comment by ybakos** [comment]
When installing **processing-java**, you should select "install for all users" or edit the path information in [Processing.sublime-build](https://github.com/b-g/processing-sublime/blob/master/Build%20Systems/Processing.sublime-build), as the comment in [Processing.sublime-build](https://github.com/b-g/processing-sublime/blob/master/Build%20Systems/Processing.sublime-build) states.

**Comment by ybakos** [comment]
@dvschultz @levitabris I have looked into this more and am now able to replicate the issue. The problem is how Sublime does not use your user shell's `PATH` configuration on OSX. To fix this, use Package Manager to install the "Fix Mac Path" package.

This occurs with Processing 3 and not Processing 2, because Processing 3 installs `processing-java` in _/usr/local/bin_ whereas Processing 2 installed it in _usr/bin_.
